[package]
name = "bookshelf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_12", "v4_14"] }
ratatui = "0.27.0"
